#!/usr/bin/env ruby

require "rubygems"
require "bundler/setup"
$LOAD_PATH.unshift File.expand_path("../../lib", __FILE__)
require "sauron"

Sauron::GmailAccount.create!(:email => ARGV[0], :password => ARGV[1])